### ISSUE TITLE
[CMake] Exception catching broken in debug (DISABLE_EXCEPTION_CATCHING=1)

### ISSUE THREAD

**Issue by forderud** [forderud/QtWasm#15]
Associated Qt issue: https://bugreports.qt.io/browse/QTBUG-110288

Startup error for CMake **debug** builds (use `debug` branch):
`Application exit (4844008 - Exception catching is disabled, this exception cannot be caught. Compile with -sNO_DISABLE_EXCEPTION_CATCHING or -sEXCEPTION_CATCHING_ALLOWED=[..] to catch.)`

Error string origin: https://github.com/emscripten-core/emscripten/blob/main/src/parseTools.js#L610

Source of configuration: ` lib/cmake/Qt6/Qt6Targets.cmake` (line 60)

## Steps to reproduce
* Switch to "debug" branch
* Run `build_cmake.bat`
* Observe that app crashes with "Exception catching is disabled" error when attempting to run in a web browser

## Things to investigate
* CMake release builds affected: No
* Qmake debug/release builds affected: No (get same problem if commenting out `QMAKE_LFLAGS += -s DISABLE_EXCEPTION_CATCHING=0`)
* Is `QT_FEATURE_thread` set: TBD

## References
* Emscripten: https://emscripten.org/docs/porting/exceptions.html
* Qt: https://doc.qt.io/qt-6/wasm.html (doesn't mention exceptions)
* Qt exception config: [Qt 6.4](https://github.com/qt/qtbase/blob/6.4/cmake/QtWasmHelpers.cmake#L31). [Qt 6.5](https://github.com/qt/qtbase/blob/6.5/cmake/QtWasmHelpers.cmake#L42)

**Comment by forderud** [comment]
Qt 6.5 change that disables exception support: https://codereview.qt-project.org/c/qt/qtbase/+/430027

**Comment by forderud** [comment]
Build step responsible for the problem:
```
[100%] Linking CXX executable helloworld.js
/usr/bin/cmake -E cmake_link_script CMakeFiles/helloworld.dir/link.txt --verbose=1
/emsdk/upstream/emscripten/em++ -g -s INITIAL_MEMORY=50MB -s EXPORTED_RUNTIME_METHODS=UTF16ToString,stringToUTF16 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s MAX_WEBGL_VERSION=2 -s FETCH=1 -s WASM_BIGINT=1 -s MODULARIZE=1 -s EXPORT_NAME=createQtAppInstance -s DISABLE_EXCEPTION_CATCHING=1 -s ALLOW_MEMORY_GROWTH=1 -s DEMANGLE_SUPPORT=1 -s GL_DEBUG=1 --profiling-funcs -sASYNCIFY_IMPORTS=qt_asyncify_suspend_js,qt_asyncify_resume_js @CMakeFiles/helloworld.dir/objects1.rsp -o helloworld.js @CMakeFiles/helloworld.dir/linklibs.rsp
```

**Comment by forderud** [comment]
This issue is still present in "debug" builds with Qt 6.5.

**Comment by qdel** [comment]
Just for the record: debug mode builds are made with a switch of -DCMAKE_BUILD_TYPE from Release to Debug.

I do reproduce the issue.
A naive comparison of the generated build.ninja files do not show anything special:

Debug use compiler -g flag while Release uses -O3 -DNDEBUG. Both have the -fexceptions flag activated
There is a switch on -DQT_NO_DEBUG but I don't think we should take care of it: we are still in our plain c++ code.

The linker flag does show an additional -s DEMANGLE_SUPPORT=1 flag which seems pretty logic.

**Comment by qdel** [comment]
Actually, the exceptions works with RelWithDebInfo mode, which uses flags -O2 -g -NDEBUG flags.
What do we except from Debug mode ? using the integrated debugger on chrome ?

We can actually do this using RelWithDebInfo mode.

**Comment by forderud** [comment]
> Actually, the exceptions works with RelWithDebInfo mode, which uses flags -O2 -g -NDEBUG flags. What do we except from Debug mode ? using the integrated debugger on chrome ?
> 
> We can actually do this using RelWithDebInfo mode.

I've now added a "steps to reproduce" section in the issue decryption above. Hope this makes the expectations more clear.

**Comment by qdel** [comment]
Please, note that qt 6.5.0-beta3 is out.

Using it allows me to have exception working in Debug-compiled program.

Also, adding `add_link_options("-gsource-map")` to the wasm.cmake for Debug builds allows us to have breakpoint / var expansion (albeit, not as pretty as I would like):
![image](https://user-images.githubusercontent.com/1213231/221539007-5eefcd7a-62b9-4798-835d-53ea980052ea.png)

**Comment by forderud** [comment]
> Also, adding `add_link_options("-gsource-map")` to the wasm.cmake for Debug builds allows us to have breakpoint / var expansion (albeit, not as pretty as I would like):

Looks like a good idea. Maybe you can submit a PR on enabling it? Don't know the compile-time & run-time consequences of enabling "source maps", so it might be that we can limit it to debug builds - at least initially.

**Comment by qdel** [comment]
I have a solution which allows us to run the webserver directly in the container.
This avoid to have complicated remapping of folders. (brower dev tools could search for /usr/local/Qt-wasm/ paths for example).

It is under-way, you can have a look here: https://github.com/qdel/QtWasm/tree/debug_webserver

Note that we could go deeper by compile Qt itself with this source-map option. But I don't think it is needed. We want to debug our app, not Qt (for now...)

**Comment by forderud** [comment]
Any specific reason for reopening this issue @qdel ? I'm from my end no longer observing exception-related problems any more.

**Comment by qdel** [comment]
I reopened because of the auto-close made by merge and we had pending discussions about debug builds.

So we can have a final "human status": now, it works !
