### ISSUE TITLE
Q_IMPORT_PLUGIN Statement Generation

### ISSUE THREAD

**Issue by sebkajeka** [forderud/QtWasm#3]
Thanks for the repo, I've managed to compile Qt Examples with CMake and get them running correctly in the browser!

One step is missing however. The build will complete however at runtime qml modules will not import correctly.

To fix this, you can use the qmake generated import.cpp files and build them, which correctly imports qml modules at runtime. 

For quickcontrols/texteditor example wasm qmake generates js_plugin_import.cpp and js_qml_plugin_import.cpp which contains the following respectively:

```// This file is autogenerated by qmake. It imports static plugin classes for
// static plugins specified using QTPLUGIN and QT_PLUGIN_CLASS.<plugin> variables.
#include <QtPlugin>
Q_IMPORT_PLUGIN(QWasmIntegrationPlugin)
Q_IMPORT_PLUGIN(QGifPlugin)
Q_IMPORT_PLUGIN(QICNSPlugin)
Q_IMPORT_PLUGIN(QICOPlugin)
Q_IMPORT_PLUGIN(QJpegPlugin)
Q_IMPORT_PLUGIN(QTgaPlugin)
Q_IMPORT_PLUGIN(QTiffPlugin)
Q_IMPORT_PLUGIN(QWbmpPlugin)
Q_IMPORT_PLUGIN(QWebpPlugin)
```
```
// This file is autogenerated by qmake. It imports static plugin classes for
// static plugins used by QML imports.
#include <QtPlugin>
Q_IMPORT_PLUGIN(QtQuick2Plugin)
Q_IMPORT_PLUGIN(QtQuickControls1Plugin)
Q_IMPORT_PLUGIN(QtQuickLayoutsPlugin)
Q_IMPORT_PLUGIN(QtQuick2DialogsPlugin)
Q_IMPORT_PLUGIN(QtQuick2WindowPlugin)
Q_IMPORT_PLUGIN(QtQmlPlugin)
Q_IMPORT_PLUGIN(QmlFolderListModelPlugin)
Q_IMPORT_PLUGIN(QmlSettingsPlugin)
Q_IMPORT_PLUGIN(QtQuick2DialogsPrivatePlugin)
Q_IMPORT_PLUGIN(QtQuick2PrivateWidgetsPlugin)
```

It looks like qmake is scanning qml files and identifying module plugins to import? Do you think it is possible to replicate this functionality in cmake?

**Comment by forderud** [comment]
Hi @sebkajeka . I'm also struggling with missing `Q_IMPORT_PLUGIN` macros in my Qt projects. You're probably right in that this can likely be automated by calling QMake from CMake. However, my CMake expertise is rather limited, so I have no clue how to achieve that.

**Comment by sebkajeka** [comment]
My knowledge of CMake is also limited although I hear file generation is a possibility. I was wondering instead of calling QMake from CMake (although that is an option) is just to fully replicate the QMake file generation in CMake. 

I'll investigate the QMake source and see how it identifies the import statements. For now I recommend people maintain their own plugin_import.cpp files.

**Comment by sebkajeka** [comment]
OK after a brief investigation I think I understand what qmake is doing in this regard.

QMake is running qt.prf, the following section is where the magic happens:
https://github.com/qt/qtbase/blob/5.14/mkspecs/features/qt.prf#L272

QMake invokes ```qmlimportscanner ./ -importPath {QT_BUILD_DIR}/qtbase/qml``` which outputs qml dependencies in json. The prf parses the json into templated .cpp files (contained within the qt.prf) and they're written out as import cpp files.

As I see it we have two options to tackle this. 

1. In CMake invoke qmlimportscanner and generate our own import files from the json.
or
2. (Assuming I understand how qmake prf works...) Extract relevant sections from qt.prf and put it into our own import.prf. Create a simple .pro file which executes our prf. Invoke QMake from CMake.

**Comment by forderud** [comment]
I just stumbled across `qt5_import_qml_plugins` (https://doc.qt.io/qt-5/qtqml-cmake-qt5-import-qml-plugins.html) that was introduced in Qt 5.14. This seems like exactly what we need 👍

**Comment by sebkajeka** [comment]
Very positive, unfortunately it looks a little half baked as it points to the Qt build direction not the install directory! It fails on my setup as it uses the wrong Qt Directory!

```-- Running qmlimportscanner to find used QML plugins. 
qmlimportscanner: No such file or directory: "/home/osboxes/qtbuild/qtbase/qml/"
```

https://bugreports.qt.io/browse/QTBUG-80843

https://github.com/qt/qtdeclarative/blob/dev/tools/qmlimportscanner/Qt5QmlImportScannerConfig.cmake.in#L32

**Comment by sebkajeka** [comment]
OK i've got it working with a bit of a hack you can edit:

```{Qt_INSTALL_DIR}/lib/cmake/Qt5QmlImportScanner/Qt5QmlImportScannerConfig.cmake``` 

file so ```qml_path``` points to the correct directory.

Should probably change the source cmake.in to fix it but as a hack I can build with cmake and imports!

**Comment by forderud** [comment]
Not sure if I follow you here. Don't see `qml_dir` anywhere in the file. Was it `CMAKE_QML_DIR` that you modified?

**Comment by sebkajeka** [comment]
Apologies, I meant ```qml_path```

**Comment by forderud** [comment]
Closing issue, since `qt_import_qml_plugins` seem to have eliminated the need for dealing directly with `Q_IMPORT_PLUGIN`
